/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  SimpleLoop as SimpleLoop
} from './components/simple-loop/simple-loop';

declare global {
  interface HTMLSimpleLoopElement extends SimpleLoop, HTMLElement {
  }
  var HTMLSimpleLoopElement: {
    prototype: HTMLSimpleLoopElement;
    new (): HTMLSimpleLoopElement;
  };
  interface HTMLElementTagNameMap {
    "simple-loop": HTMLSimpleLoopElement;
  }
  interface ElementTagNameMap {
    "simple-loop": HTMLSimpleLoopElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "simple-loop": JSXElements.SimpleLoopAttributes;
    }
  }
  namespace JSXElements {
    export interface SimpleLoopAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
